// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgclekYFh7W_Zui9NF7qxtcgS4B_NfXg8',
    appId: '1:709159862006:web:ff723dc8570d41f099f6d7',
    messagingSenderId: '709159862006',
    projectId: 'swagin-b2fca',
    authDomain: 'swagin-b2fca.firebaseapp.com',
    storageBucket: 'swagin-b2fca.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvS9mwKvPv6KOh8ZIAYCmInBqwXBi0PJM',
    appId: '1:709159862006:android:207b8e6eb5c7d06c99f6d7',
    messagingSenderId: '709159862006',
    projectId: 'swagin-b2fca',
    storageBucket: 'swagin-b2fca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfyJLzwi-DDJs0yuM7zQ0HnKEYhy97BWw',
    appId: '1:709159862006:ios:525d72b955d36d7d99f6d7',
    messagingSenderId: '709159862006',
    projectId: 'swagin-b2fca',
    storageBucket: 'swagin-b2fca.appspot.com',
    iosBundleId: 'com.example.swagIn',
  );
}
